### ISSUE TITLE
Mouse event is broken on firefox

### ISSUE THREAD

**Issue by coderguy57** [TodePond/ScreenPond#39]
The scrolling event: `on.mousewheel` doesn't work in firefox, should be `on.mouse` instead which works on both firefox and chrome :D
The performance is in general much worse on firefox, no idea why :thinking: 

Also a minor thing that's would be nice is to allow both normal scrolling and the current automatic scrolling with the set speed. Cause it's quite hard to stop scrolling right now :)

**Comment by TodePond** [comment]
Cool, thanks for letting me know! I can fix that after the weekend.

the camera zoom is really weird at the moment because I'm using it to record some smooth shots for the video, but it would be good to have a normal zoom available too. I'll make an issue for it. By the way, you can press "R" to reset the desired zoom speed to 0 again (it might take a while to slow down though)

**Comment by TodePond** [comment]
Mousewheel should work in firefox now!
